/** Created by Denis Abramyan (dennila2@gmail.com) on 01.12.2024 */

export enum EMessageEvent {
  PROCESS_BOOK_PAGES = 'PROCESS_BOOK_PAGES',
  OPEN_OPTIONS_WINDOW = 'OPEN_OPTIONS_WINDOW',
  COLLECT_BK_TABS = 'COLLECT_BK_TABS',
  ON_BK_TABS_COLLECTED = 'ON_BK_TABS_COLLECTED',
}
