/** Created by Denis Abramyan (dennila2@gmail.com) on 01.12.2024 */

export enum EMessageEvent {
  PROCESS_BOOK_PAGES = 'PROCESS_BOOK_PAGES',
  OPEN_OPTIONS_WINDOW = 'OPEN_OPTIONS_WINDOW',
  COLLECT_BK_TABS = 'COLLECT_BK_TABS',
  ON_BK_TABS_COLLECTED = 'ON_BK_TABS_COLLECTED',
  // OPTIONS_TO_BG__PROCESS_BOOKS = 'OPTIONS_TO_BG__PROCESS_BOOKS',
  // BG_TO_OPTIONS__ON_BOOKS_PROCESS_PROGRESS = 'BG_TO_OPTIONS__ON_BOOKS_PROCESS_PROGRESS',
  // SCRIPT_TO_BG__TORRENT_FILE_NAME = 'SCRIPT_TO_BG__TORRENT_FILE_NAME',
  // BG_TO_SCRIPT__TORRENT_DOWNLOADED = 'BG_TO_SCRIPT__TORRENT_DOWNLOADED',
}
